language: node_js
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
services:
  - redis-server
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
  - npm install -g node-pre-gyp
install:
  - npm install
#  - npm prune // Broken because of https://github.com/npm/npm/issues/17781
  - cd node_modules; mkdir @rheactorjs; cd @rheactorjs; ln -s ../../ server; cd ../../
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npm run lint
  - make dist
  - npm run test:coverage-travis
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
matrix:
  include:
#    - node_js: 'node'
    - node_js: '6'
